name: Feature Request
description: Suggest an idea for BulkIG
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: This feature would help with...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How should this feature work? Be as detailed as possible.
      placeholder: The feature should work by...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area of BulkIG would this feature affect?
      options:
        - UI/Dashboard
        - Scheduling System
        - Content Management
        - AI/Caption Generation
        - Instagram Integration
        - Analytics/Reporting
        - Configuration/Settings
        - API/Integrations
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for daily use
        - Critical - Blocking current usage
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've considered...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If you have mockups, screenshots, or examples from other tools, please include them.
      placeholder: Drag and drop images here or paste links...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, links, or information about the feature request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: This feature aligns with BulkIG's purpose and scope
          required: true
        - label: I have provided sufficient detail for implementation
          required: true